# Permalinks
permalink:           pretty

# Setup
title:               BDB
tagline:             Big Data Blog
url:                 https://joeyfaherty.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Joey Faherty
  url:               https://joeyfaherty.github.io/
  email:             joeyfaherty@live.ie

# Custom vars
version:             1.0.0
github:
  repo:              https://joeyfaherty.github.io/

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

pages_list:
  About: '/about'
  Archive: '/archive'
